name: hello-world
'on': push
jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World from ubuntu!"
  windows-job:
    runs-on: windows-latest
    steps:
      - name: my-step
        run: echo "Hello World from windows!"
  mac-job:
    runs-on: macos-latest
    steps:
      - name: my-step
        run: echo "Hello World from macos!"
